"""criação das tabelas no ssms

Revision ID: 32a660d9c42c
Revises: 
Create Date: 2025-05-07 16:12:53.293876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a660d9c42c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cargo',
    sa.Column('idCargo', sa.Integer(), nullable=False),
    sa.Column('nome_cargo', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('idCargo')
    )
    op.create_table('Genitor',
    sa.Column('RG', sa.CHAR(length=15), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('sexo', sa.CHAR(length=1), nullable=False),
    sa.Column('dt_nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.CHAR(length=15), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('RG')
    )
    op.create_table('Bebe',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('Genitor_mae_RG', sa.CHAR(length=15), nullable=False),
    sa.Column('Genitor_pai_RG', sa.CHAR(length=15), nullable=True),
    sa.Column('dthr_nasc', sa.DateTime(), nullable=False),
    sa.Column('sexo', sa.CHAR(length=1), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('tipo_parto', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['Genitor_mae_RG'], ['Genitor.RG'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Genitor_pai_RG'], ['Genitor.RG'], ),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('Profissional_saude',
    sa.Column('CPF', sa.CHAR(length=11), nullable=False),
    sa.Column('RG', sa.CHAR(length=15), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('dt_nasc', sa.DateTime(), nullable=True),
    sa.Column('registro', sa.CHAR(length=45), nullable=True),
    sa.Column('Cargo_idCargo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Cargo_idCargo'], ['Cargo.idCargo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CPF')
    )
    op.create_table('Profissional_saude_has_Bebe',
    sa.Column('Profissional_saude_CPF', sa.CHAR(length=11), nullable=False),
    sa.Column('Bebe_nome', sa.String(length=200), nullable=False),
    sa.Column('Bebe_Genitor_mae_RG', sa.CHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['Bebe_Genitor_mae_RG'], ['Genitor.RG'], ),
    sa.ForeignKeyConstraint(['Bebe_nome'], ['Bebe.nome'], ),
    sa.ForeignKeyConstraint(['Profissional_saude_CPF'], ['Profissional_saude.CPF'], ),
    sa.PrimaryKeyConstraint('Profissional_saude_CPF', 'Bebe_nome', 'Bebe_Genitor_mae_RG')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Profissional_saude_has_Bebe')
    op.drop_table('Profissional_saude')
    op.drop_table('Bebe')
    op.drop_table('Genitor')
    op.drop_table('Cargo')
    # ### end Alembic commands ###
